### ISSUE TITLE
Discogs API Endpoints Checklist

### ISSUE THREAD

**Issue by rex** [buntine/discogs#27]
As per my comment in https://github.com/buntine/discogs/issues/22#issuecomment-43236776, below is the totality of the Discogs API endpoints. I figure as they are started a comment should be made to this issue indicating which endpoint you are working on and when complete @buntine can check them off.
- [x] **GET** `/artists/:id`
- [x] **GET** `/artists/:id/releases`
- [x] **GET** `/releases/:id`
- [x] **GET** `/masters/:id`
- [x] **GET** `/masters/:id/versions`
- [x] **GET** `/labels/:id`
- [x] **GET** `/labels/:id/releases`
- [x] **GET** `/images/:filename`
- [x] **GET** `/database/search`
- [x] **GET** `/users/:username/collection/folders/0/releases`
- [x] **GET** `/users/:username/wants`
